In [3]:
import numpy as np
import pandas as pd

datos = [1,2,3,4]
indice = ["Enero", "Febrero","Marzo","Abril"]

serie = pd.Series(datos, index=indice)
serie

datos_diccionario = {"Enero":11, "Febrero":22,"Marzo":33,"Abril":44}

serie = pd.Series(datos_diccionario)
serie

Enero      11
Febrero    22
Marzo      33
Abril      44
dtype: int64

In [ ]:
serie = pd.Series([1,2,3,4], index=["a","b","c","d"])
print("Indice de la serie", serie.index)
print("Valor asociado al indice 'c':",serie["c"])

Indice de la serie Index(['a', 'b', 'c', 'd'], dtype='object')
Valor asociado al indice 'c': 3

In [8]:
serie = pd.Series([1,2,3,4,5,6,7,8,9], index=["a","b","c","d","c","e","f","g","c"])
print("Indice de la serie", serie.index)
print("Valores asociados al indice 'c':")
print(serie["c"])

Indice de la serie Index(['a', 'b', 'c', 'd', 'c', 'e', 'f', 'g', 'c'], dtype='object')
Valores asociados al indice 'c':
c    3
c    5
c    9
dtype: int64

In [27]:
serie = pd.Series([1,2,3,4,5,6,7,8,9], index=["a","b","c","d","e","f","g","h","i"])
print("Valor item de la posicion 5:", serie.iloc[4])

Valor item de la posicion 5: 5

In [32]:
serie = pd.Series([1,2,3,4,5,6,7,8,9], index=["a","b","c","d","e","f","g","h","i"])
serie.iloc[3:6]

d    4
e    5
f    6
dtype: int64

In [9]:
serie = pd.Series([1,2,3,4,5,6,7,8,9], index=["a","b","c","d","e","f","g","h","i"])
print(serie.iloc[2:8])
serie.iloc[2:8][1:3]

c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64

d    4
e    5
dtype: int64

In [44]:
import pandas as pd

# Crear un rango de 10 días a partir de una fecha
fechas = pd.date_range(start='2024-01-01', periods=10, freq='W')
fechas

DatetimeIndex(['2024-01-07', '2024-01-14', '2024-01-21', '2024-01-28',
               '2024-02-04', '2024-02-11', '2024-02-18', '2024-02-25',
               '2024-03-03', '2024-03-10'],
              dtype='datetime64[ns]', freq='W-SUN')

In [1]:
import numpy as np
import pandas as pd

datos = {"Entradas": [41,32,56,18], 
         "Salidas": [17,54,6,78],
         "Valoracion": ["No","Si","No","No"],
         "Limite": [1.45,1.16,-0.67,0.77],
         "Cambio": [66,54,49,66]
        }
indice = ["Ene","Feb","Mar","Abr"]

ventas = pd.DataFrame(datos, index=indice) 
ventas

     Entradas  Salidas Valoracion  Limite  Cambio
Ene        41       17         No    1.45      66
Feb        32       54         Si    1.16      54
Mar        56        6         No   -0.67      49
Abr        18       78         No    0.77      66

In [15]:
print("Tipo de los datos:")
print(ventas.dtypes)
print("\nIndice del dataframe:", ventas.index)
print("\nNombre de las columnas")
print(ventas.columns)
print("\nEjes del dataframe:", "\nEje X →", ventas.axes[0], "\nEje Y →", ventas.axes[1])
print("\nContenido del dataframe:")
print(ventas.values)
print("\nForma del dataframe:")
print(ventas.shape)

Tipo de los datos:
Entradas        int64
Salidas         int64
Valoracion     object
Limite        float64
Cambio          int64
dtype: object

Indice del dataframe: Index(['Ene', 'Feb', 'Mar', 'Abr'], dtype='object')

Nombre de las columnas
Index(['Entradas', 'Salidas', 'Valoracion', 'Limite', 'Cambio'], dtype='object')

Ejes del dataframe:
Eje X → Index(['Ene', 'Feb', 'Mar', 'Abr'], dtype='object')
Eje Y → Index(['Entradas', 'Salidas', 'Valoracion', 'Limite', 'Cambio'], dtype='object')

Contenido del dataframe:
[[41 17 'No' 1.45 66]
 [32 54 'Si' 1.16 54]
 [56 6 'No' -0.67 49]
 [18 78 'No' 0.77 66]]

Forma del dataframe:
(4, 5)

In [28]:
dataframe = pd.DataFrame(np.arange(40).reshape(10,4), columns=list('abcd'), index=list('ABCDEFGHIJ'))
dataframe
print(list('abcd'))
dataframe.rename_axis("Letras minusculas",axis=1)

['a', 'b', 'c', 'd']

Letras minusculas   a   b   c   d
A                   0   1   2   3
B                   4   5   6   7
C                   8   9  10  11
D                  12  13  14  15
E                  16  17  18  19
F                  20  21  22  23
G                  24  25  26  27
H                  28  29  30  31
I                  32  33  34  35
J                  36  37  38  39

In [44]:
dataframe = pd.read_csv("https://datahub.io/core/covid-19/_r/-/data/countries-aggregated.csv", sep=',')
dataframe

              Date      Country  Confirmed  Recovered  Deaths
0       2020-01-22  Afghanistan          0          0       0
1       2020-01-23  Afghanistan          0          0       0
2       2020-01-24  Afghanistan          0          0       0
3       2020-01-25  Afghanistan          0          0       0
4       2020-01-26  Afghanistan          0          0       0
...            ...          ...        ...        ...     ...
161563  2022-04-12     Zimbabwe     247094          0    5460
161564  2022-04-13     Zimbabwe     247160          0    5460
161565  2022-04-14     Zimbabwe     247208          0    5462
161566  2022-04-15     Zimbabwe     247237          0    5462
161567  2022-04-16     Zimbabwe     247237          0    5462

[161568 rows x 5 columns]

In [50]:
# dataframe = pd.read_csv("petrol_consumption.csv", sep=',')
dataframe = pd.read_excel("canarias.xlsx")
dataframe

c:\Users\titan\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,TERRITORIO#es,TERRITORIO_CODE,TIME_PERIOD#es,TIME_PERIOD_CODE,SEXO#es,SEXO_CODE,GRUPO_EDAD#es,GRUPO_EDAD_CODE,DIAGNOSTICO_PRINCIPAL#es,DIAGNOSTICO_PRINCIPAL_CODE,MEDIDAS#es,MEDIDAS_CODE,OBS_VALUE,NOTAS_OBSERVACION#es,CONFIDENCIALIDAD_OBSERVACION#es,ESTADO_OBSERVACION#es,ESTADO_OBSERVACION_CODE
0,Canarias,ES70,2020,2020,Total,_T,Total,_T,Total,_T,Estancia media,ESTANCIA_MEDIA,12.29,NaN,NaN,NaN,NaN
1,Canarias,ES70,2020,2020,Hombres,M,Total,_T,Total,_T,Estancia media,ESTANCIA_MEDIA,13.10,NaN,NaN,NaN,NaN
2,Canarias,ES70,2020,2020,Mujeres,F,Total,_T,Total,_T,Estancia media,ESTANCIA_MEDIA,11.55,NaN,NaN,NaN,NaN
3,Canarias,ES70,2021,2021,Total,_T,Total,_T,Total,_T,Estancia media,ESTANCIA_MEDIA,12.18,NaN,NaN,NaN,NaN
4,Canarias,ES70,2021,2021,Hombres,M,Total,_T,Total,_T,Estancia media,ESTANCIA_MEDIA,13.08,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16303,Santa Cruz de Tenerife,ES702,2022,2022,Hombres,M,Total,_T,0100 Ciertas enfermedades infecciosas y parasi...,0100,Altas,ALTAS,2769.00,NaN,NaN,NaN,NaN
16304,Santa Cruz de Tenerife,ES702,2022,2022,Mujeres,F,Total,_T,0100 Ciertas enfermedades infecciosas y parasi...,0100,Altas,ALTAS,2727.00,NaN,NaN,NaN,NaN
16305,Santa Cruz de Tenerife,ES702,2023,2023,Total,_T,Total,_T,0100 Ciertas enfermedades infecciosas y parasi...,0100,Altas,ALTAS,3495.00,NaN,NaN,NaN,NaN
16306,Santa Cruz de Tenerife,ES702,2023,2023,Hombres,M,Total,_T,0100 Ciertas enfermedades infecciosas y parasi...,0100,Altas,ALTAS,1758.00,NaN,NaN,NaN,NaN
16307,Santa Cruz de Tenerife,ES702,2023,2023,Mujeres,F,Total,_T,0100 Ciertas enfermedades infecciosas y parasi...,0100,Altas,ALTAS,1737.00,NaN,NaN,NaN,NaN

In [64]:
dataframe = pd.read_parquet("yellow_tripdata.parquet")
# dataframe.columns
dataframe["tip_amount"].mean()
# dataframe.describe()

np.float64(2.9598127862763457)